name: Build Hugo to docs folder

on:
  push:
    branches: [master]  # or main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build to docs
        run: hugo --minify -d docs

      - name: Commit and Push docs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs
          git commit -m "Auto-build site to docs" || echo "No changes to commit"
          git push origin master